### ISSUE TITLE
Rebranding

### ISSUE THREAD

**Issue by rmariuzzo** [developersdo/DevelopersDo.DataAnnotations#6]
Update any "Mariuzzo" references across the code base:

 - `Mariuzzo.DO.DataAnnotations` > `DevelopersDo.DataAnnotations`.

**Comment by EfrainReyes** [comment]
See #7

**Comment by rmariuzzo** [comment]
@EfrainReyes this looks awesome.

**Comment by EfrainReyes** [comment]
Sure, let's do that tomorrow.

**Comment by EfrainReyes** [comment]
@hminaya dame poderex please

**Comment by EfrainReyes** [comment]
@rmariuzzo Not sure if NuGet lets you do  a whole rebrand so I pushed the update here with a new version: https://www.nuget.org/packages/DevelopersDo.DataAnnotations/

Just waiting for the powers that be to grant me the ability to rename the repository

**Comment by carlosvasquez** [comment]
listo

**Comment by EfrainReyes** [comment]
Gracias @carlosvasquez 

@rmariuzzo ya todo esta listo, I think we can go forward with the merge, what do you say?

**Comment by rmariuzzo** [comment]
Where is the branch @EfrainReyes ?

**Comment by EfrainReyes** [comment]
Here: #7 @rmariuzzo
