### ISSUE TITLE
Cedulas que no cumplen con el criterio de evaluación

### ISSUE THREAD

**Issue by nramirez** [developersdo/DevelopersDo.DataAnnotations#8]
Hice una prueba de integración con las cédulas y me confirmé algo que me paso hace un tiempo con este algoritmo. Hay un conjunto de cédulas que no cumplen con el criterio del algoritmo de Luhn, pero que aun así, son cédulas vigentes y asignadas a individuos actualmente.

Aqui hice un gist con dichas cédulas: https://gist.github.com/nramirez/c1c7cd21c0914b18d13e

Creo que seria bueno considerarlas en la validacion,  ¿Que opinan?

**Comment by EfrainReyes** [comment]
@nramirez le hice un code review a tu PR.
